In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [2]:
dataset = pd.read_excel('mauxuong.ods', engine='odf')

In [3]:
dataset

Tên Mẫu CL  PL Loại I Loại II Loại III Loại IV Loại V Loại VI Loại VII  \
0    TVAA0501  C   2     I3     II3     III3     IV2     V3     VI3     VII2   
1    TVAA0503  D   2     I3     II4     III2     NaN     V4     VI4     VII3   
2    TVAA0508  D   2     I3     II4     III2     NaN     V4     VI4     VII3   
3    TVAA0509  D   2     I3     II4     III2     NaN     V4     VI3     VII3   
4    TVAA0602  C   3     I3     II3     III2     IV1     V3     VI3     VII2   
..        ... ..  ..    ...     ...      ...     ...    ...     ...      ...   
426  YCB08108  C   3     I1     II2     III1     NaN     V2     VI3     VII2   
427  YCB10114  C   3     I2     II2     III2     NaN     V2     VI3     VII2   
428  YCB11120  C   3     I3     II3     III2     NaN     V2     VI3     VII2   
429  YCB12123  D   3     I3     II3     III2     NaN     V4     VI4     VII2   
430  YCB12124  C   3     I3     II3     III2     NaN     V3     VI3     VII2   

    Loại Trả Kết quả  
0      X         NaN  
1      R         NaN  
2      R         NaN  
3      R         NaN  
4      X         NaN  
..   ...         ...  
426    R          có  
427    R          có  
428    R          có  
429    X         NaN  
430    X         NaN  

[431 rows x 12 columns]

In [4]:
name = ['Tên Mẫu','Loại I', 'Loại II', 'Loại III', 'Loại IV', 'Loại V', 'Loại VI', 'Loại VII', 'Loại', 'Trả Kết quả']
name_change = ['Sample', 'Loai I', 'Loai II', 'Loai III', 'Loai IV', 'Loai V', 'Loai VI', 'Loai VII', 'Loai', 'Result']

In [5]:
dataset = dataset.rename(columns={x : y for x, y in zip(name, name_change)})

In [6]:
dataset.head()

Sample CL  PL Loai I Loai II Loai III Loai IV Loai V Loai VI Loai VII  \
0  TVAA0501  C   2     I3     II3     III3     IV2     V3     VI3     VII2   
1  TVAA0503  D   2     I3     II4     III2     NaN     V4     VI4     VII3   
2  TVAA0508  D   2     I3     II4     III2     NaN     V4     VI4     VII3   
3  TVAA0509  D   2     I3     II4     III2     NaN     V4     VI3     VII3   
4  TVAA0602  C   3     I3     II3     III2     IV1     V3     VI3     VII2   

  Loai Result  
0    X    NaN  
1    R    NaN  
2    R    NaN  
3    R    NaN  
4    X    NaN

In [7]:
# dataset = dataset.fillna(0)

In [8]:
dataset

Sample CL  PL Loai I Loai II Loai III Loai IV Loai V Loai VI Loai VII  \
0    TVAA0501  C   2     I3     II3     III3     IV2     V3     VI3     VII2   
1    TVAA0503  D   2     I3     II4     III2     NaN     V4     VI4     VII3   
2    TVAA0508  D   2     I3     II4     III2     NaN     V4     VI4     VII3   
3    TVAA0509  D   2     I3     II4     III2     NaN     V4     VI3     VII3   
4    TVAA0602  C   3     I3     II3     III2     IV1     V3     VI3     VII2   
..        ... ..  ..    ...     ...      ...     ...    ...     ...      ...   
426  YCB08108  C   3     I1     II2     III1     NaN     V2     VI3     VII2   
427  YCB10114  C   3     I2     II2     III2     NaN     V2     VI3     VII2   
428  YCB11120  C   3     I3     II3     III2     NaN     V2     VI3     VII2   
429  YCB12123  D   3     I3     II3     III2     NaN     V4     VI4     VII2   
430  YCB12124  C   3     I3     II3     III2     NaN     V3     VI3     VII2   

    Loai Result  
0      X    NaN  
1      R    NaN  
2      R    NaN  
3      R    NaN  
4      X    NaN  
..   ...    ...  
426    R     có  
427    R     có  
428    R     có  
429    X    NaN  
430    X    NaN  

[431 rows x 12 columns]

In [9]:
loai1 = np.unique(dataset['Loai I'].astype('str'))
loai2 = np.unique(dataset['Loai II'].astype('str'))
loai3 = np.unique(dataset['Loai III'].astype('str'))
loai4 = np.unique(dataset['Loai IV'].astype('str'))
loai5 = np.unique(dataset['Loai V'].astype('str'))
loai6 = np.unique(dataset['Loai VI'].astype('str'))
loai7 = np.unique(dataset['Loai VII'].astype('str'))
loai = np.unique(dataset['Loai'].astype('str'))
result = np.unique(dataset['Result'].astype('str'))


In [10]:
print(loai1, loai2, loai3, loai4, loai5, loai6, loai7, loai, result)

['I1' 'I2' 'I3'] ['II2' 'II3' 'II4'] ['III1' 'III2' 'III3' 'nan'] ['IV1' 'IV2' 'IV3' 'nan'] ['V2' 'V3' 'V4'] ['VI2' 'VI3' 'VI4'] ['VII1' 'VII2' 'VII3' 'VII4'] ['R' 'X'] ['có' 'nan']


In [11]:
def cvtlabelStringtoNumber(list_type_convert, name_change, dataset):
    for (type, name) in zip(list_type_convert, name_change):
        type_mapping = {x : int(x[-1]) for x in type if (x != 'nan')}
        dataset[name] = dataset[name].map(type_mapping)
        dataset[name] = dataset[name].fillna(0)
        dataset[name] = dataset[name].astype('int')
        print(type_mapping)

In [12]:
name_cvt = ['Loai I', 'Loai II', 'Loai III', 'Loai IV', 'Loai V', 'Loai VI', 'Loai VII']
list_type_convert = [loai1, loai2, loai3, loai4, loai5, loai6, loai7]
cvtlabelStringtoNumber(list_type_convert=list_type_convert, name_change=name_cvt, dataset=dataset)

{'I1': 1, 'I2': 2, 'I3': 3}
{'II2': 2, 'II3': 3, 'II4': 4}
{'III1': 1, 'III2': 2, 'III3': 3}
{'IV1': 1, 'IV2': 2, 'IV3': 3}
{'V2': 2, 'V3': 3, 'V4': 4}
{'VI2': 2, 'VI3': 3, 'VI4': 4}
{'VII1': 1, 'VII2': 2, 'VII3': 3, 'VII4': 4}


In [13]:
dataset

Sample CL  PL  Loai I  Loai II  Loai III  Loai IV  Loai V  Loai VI  \
0    TVAA0501  C   2       3        3         3        2       3        3   
1    TVAA0503  D   2       3        4         2        0       4        4   
2    TVAA0508  D   2       3        4         2        0       4        4   
3    TVAA0509  D   2       3        4         2        0       4        3   
4    TVAA0602  C   3       3        3         2        1       3        3   
..        ... ..  ..     ...      ...       ...      ...     ...      ...   
426  YCB08108  C   3       1        2         1        0       2        3   
427  YCB10114  C   3       2        2         2        0       2        3   
428  YCB11120  C   3       3        3         2        0       2        3   
429  YCB12123  D   3       3        3         2        0       4        4   
430  YCB12124  C   3       3        3         2        0       3        3   

     Loai VII Loai Result  
0           2    X    NaN  
1           3    R    NaN  
2           3    R    NaN  
3           3    R    NaN  
4           2    X    NaN  
..        ...  ...    ...  
426         2    R     có  
427         2    R     có  
428         2    R     có  
429         2    X    NaN  
430         2    X    NaN  

[431 rows x 12 columns]

In [14]:
type = LabelEncoder()
type.fit(loai)
type.classes_

array(['R', 'X'], dtype=object)

In [15]:
type.transform(loai)

array([0, 1])

In [16]:
dataset['Loai'] = type.fit_transform(dataset['Loai']) + 1

In [17]:
dataset

Sample CL  PL  Loai I  Loai II  Loai III  Loai IV  Loai V  Loai VI  \
0    TVAA0501  C   2       3        3         3        2       3        3   
1    TVAA0503  D   2       3        4         2        0       4        4   
2    TVAA0508  D   2       3        4         2        0       4        4   
3    TVAA0509  D   2       3        4         2        0       4        3   
4    TVAA0602  C   3       3        3         2        1       3        3   
..        ... ..  ..     ...      ...       ...      ...     ...      ...   
426  YCB08108  C   3       1        2         1        0       2        3   
427  YCB10114  C   3       2        2         2        0       2        3   
428  YCB11120  C   3       3        3         2        0       2        3   
429  YCB12123  D   3       3        3         2        0       4        4   
430  YCB12124  C   3       3        3         2        0       3        3   

     Loai VII  Loai Result  
0           2     2    NaN  
1           3     1    NaN  
2           3     1    NaN  
3           3     1    NaN  
4           2     2    NaN  
..        ...   ...    ...  
426         2     1     có  
427         2     1     có  
428         2     1     có  
429         2     2    NaN  
430         2     2    NaN  

[431 rows x 12 columns]

In [18]:
dataset

Sample CL  PL  Loai I  Loai II  Loai III  Loai IV  Loai V  Loai VI  \
0    TVAA0501  C   2       3        3         3        2       3        3   
1    TVAA0503  D   2       3        4         2        0       4        4   
2    TVAA0508  D   2       3        4         2        0       4        4   
3    TVAA0509  D   2       3        4         2        0       4        3   
4    TVAA0602  C   3       3        3         2        1       3        3   
..        ... ..  ..     ...      ...       ...      ...     ...      ...   
426  YCB08108  C   3       1        2         1        0       2        3   
427  YCB10114  C   3       2        2         2        0       2        3   
428  YCB11120  C   3       3        3         2        0       2        3   
429  YCB12123  D   3       3        3         2        0       4        4   
430  YCB12124  C   3       3        3         2        0       3        3   

     Loai VII  Loai Result  
0           2     2    NaN  
1           3     1    NaN  
2           3     1    NaN  
3           3     1    NaN  
4           2     2    NaN  
..        ...   ...    ...  
426         2     1     có  
427         2     1     có  
428         2     1     có  
429         2     2    NaN  
430         2     2    NaN  

[431 rows x 12 columns]

In [19]:
map_res = {'có' : 1}
dataset['Result'] = dataset['Result'].map(map_res)
dataset['Result'] = dataset['Result'].fillna(0)
dataset['Result'] = dataset['Result'].astype('int')

In [20]:
dataset

Sample CL  PL  Loai I  Loai II  Loai III  Loai IV  Loai V  Loai VI  \
0    TVAA0501  C   2       3        3         3        2       3        3   
1    TVAA0503  D   2       3        4         2        0       4        4   
2    TVAA0508  D   2       3        4         2        0       4        4   
3    TVAA0509  D   2       3        4         2        0       4        3   
4    TVAA0602  C   3       3        3         2        1       3        3   
..        ... ..  ..     ...      ...       ...      ...     ...      ...   
426  YCB08108  C   3       1        2         1        0       2        3   
427  YCB10114  C   3       2        2         2        0       2        3   
428  YCB11120  C   3       3        3         2        0       2        3   
429  YCB12123  D   3       3        3         2        0       4        4   
430  YCB12124  C   3       3        3         2        0       3        3   

     Loai VII  Loai  Result  
0           2     2       0  
1           3     1       0  
2           3     1       0  
3           3     1       0  
4           2     2       0  
..        ...   ...     ...  
426         2     1       1  
427         2     1       1  
428         2     1       1  
429         2     2       0  
430         2     2       0  

[431 rows x 12 columns]

In [24]:
quality = LabelEncoder()
quality.fit(dataset['CL'])
quality.transform(dataset['CL']) + 1

array([2, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 3, 2, 2, 3, 2, 3, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       2, 3, 2, 3, 3, 2, 3, 2, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2, 3, 2, 2, 1,
       2, 2, 2, 3, 2, 3, 2, 2, 3, 2, 3, 3, 2, 3, 2, 3, 2, 3, 2, 2, 2, 3,
       3, 3, 3, 3, 3, 2, 3, 2, 3, 2, 3, 3, 2, 3, 2, 2, 3, 2, 3, 3, 3, 2,
       3, 3, 2, 2, 2, 2, 2, 2, 2, 3, 3, 2, 2, 3, 3, 3, 2, 3, 2, 2, 3, 3,
       2, 2, 3, 3, 2, 2, 2, 2, 3, 2, 3, 3, 2, 3, 3, 3, 2, 3, 2, 2, 3, 2,
       2, 2, 3, 3, 2, 2, 2, 2, 2, 2, 3, 3, 3, 2, 2, 2, 3, 2, 2, 2, 3, 2,
       3, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2,
       2, 3, 2, 1, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 3, 3, 3, 2, 3, 2, 3, 3,
       2, 2, 2, 2, 2, 3, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 3, 2,
       3, 2, 2, 3, 2, 2, 3, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2, 3, 2,
       2, 2, 2, 3, 2, 2, 3, 2, 3, 2, 2, 2, 2, 2, 3, 3, 2, 2, 3, 2, 3, 3,
       2, 3, 2, 2, 2, 3, 2, 2, 3, 2, 2, 2, 3, 2, 2,

In [25]:
quality.transform(dataset['CL'])

array([1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       1, 2, 1, 2, 2, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0,
       1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 2, 2, 2, 1,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2,
       1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 1, 1, 2, 1,
       1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1,
       2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 0, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2,
       1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1,
       2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2,
       1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1,

In [27]:
quality = list(np.unique(dataset['CL']))

In [29]:
dist = {x : (i + 1) for (x, i) in zip(quality, range(1, len(quality) + 1))}

In [30]:
dist

{'B': 2, 'C': 3, 'D': 4}

In [31]:
dataset['CL'] = dataset['CL'].map(dist)

In [32]:
dataset

Sample  CL  PL  Loai I  Loai II  Loai III  Loai IV  Loai V  Loai VI  \
0    TVAA0501   3   2       3        3         3        2       3        3   
1    TVAA0503   4   2       3        4         2        0       4        4   
2    TVAA0508   4   2       3        4         2        0       4        4   
3    TVAA0509   4   2       3        4         2        0       4        3   
4    TVAA0602   3   3       3        3         2        1       3        3   
..        ...  ..  ..     ...      ...       ...      ...     ...      ...   
426  YCB08108   3   3       1        2         1        0       2        3   
427  YCB10114   3   3       2        2         2        0       2        3   
428  YCB11120   3   3       3        3         2        0       2        3   
429  YCB12123   4   3       3        3         2        0       4        4   
430  YCB12124   3   3       3        3         2        0       3        3   

     Loai VII  Loai  Result  
0           2     2       0  
1           3     1       0  
2           3     1       0  
3           3     1       0  
4           2     2       0  
..        ...   ...     ...  
426         2     1       1  
427         2     1       1  
428         2     1       1  
429         2     2       0  
430         2     2       0  

[431 rows x 12 columns]

In [33]:
dataset.to_excel('mauxuong_preprocessing.ods')
dataset.to_excel('excel_mauxuong_preprocessing.xlsx')

# Decode String -> Int
- LoaiI (0 ,I1, I2, I3, ...) -> (1, 2, 3, ...)
- LoaiII (II1, II2, II3, ...) -> (1, 2, 3, ...)
- Loai (R, X) -> (1, 2)
- Result (khong, co) -> (0, 1)
- CL (A, B, C, D ...) -> (1, 2, 3, 4 ...)